# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
