# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20190221_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventJoinBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_join_by_user', to=settings.AUTH_USER_MODEL)),
                ('EventJoinId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_join_id', to='events.Event')),
            ],
        ),
    ]
