# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-20 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='views',
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
