# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='processed',
        ),
    ]
